name: scraper
channels:
  - conda-forge
  - defaults
dependencies:
  - bidict
  - coverage
  - pip
  - pydantic=1.10
  - pytest
  - python=3.10
  - ujson
  - zlib
  - pip:
      - selenium==4.1.0
      - webdriver-manager==3.2.2
      - selenium-wire==5.1.0
      - python-dateutil==2.8.2
      - python-dotenv==1.0.1
      - aiohttp==3.10.3
      - pydantic==1.10.7
      - blinker==1.7.0
      - docker==5.0.3
      - dotmap==1.3.30
      - flake8==3.7.9
      - gql
      - grpcio-tools
      - importlib-metadata==0.23
      - injective-py==1.4.*
      - jsonpickle==3.0.1
      - pre-commit==2.18.1
      - ruamel-yaml==0.16.10
      - appdirs==1.4.3

