#!/bin/bash


# Check if bin/main.py exists
if [[ ! -f bin/main.py ]]; then
    echo "Error: bin/main.py command not found. Make sure you are in the root directory"
    exit 1
fi

source activate scraper

# Check if the conda environment is activated
if [[ $CONDA_DEFAULT_ENV != "scraper" ]]; then
    echo "Error: 'scraper' conda environment is not activated. Please activate it and try again."
    exit 1
fi

# Build the command to run
CMD="python ./bin/main.py"

if [[ ! -z "$FILENAME" ]]; then
    CMD="$CMD -f \"$FILENAME\""
fi

# Clear the errors.log file first before executing
> ./logs/errors.log

# Execute the command
eval $CMD 2>> ./logs/errors.log

if grep -q "FileNotFoundError" ./logs/errors.log; then
    echo "Error: Invalid file or filename provided."
    exit 2
fi
